apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: crossplane-system
stringData:
  password: admin123
---
apiVersion: aerospike.terasky.com/v1alpha1
kind: User
metadata:
  name: test-user
spec:
  forProvider:
    passwordSecretRef:
      key: password
      name: auth-secret
      namespace: crossplane-system
    roles:
    - data-admin
    - read-write

